# EP4210 Computational Physics
Class on Jan 3 2025

Computational Methods for Physics - Joe Frankilin

## Basics

In [1]:
import math
math.exp(3)

20.085536923187668

In [2]:
import numpy as np
np.sqrt(2)

np.float64(1.4142135623730951)

In [3]:
np.sin(np.pi/2) # in rads

np.float64(1.0)

## Lists

In [4]:
list = [1, 2, 3, 4]
print(list)

[1, 2, 3, 4]


## Numpy Array

In [5]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
for i in range(0, 10):
    a[i] = i
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [7]:
cou = 0
for i in a:
    i = cou # this doesnt change array value
    cou += 2
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
np.exp(a[:2])

array([1.        , 2.71828183])

## Matrices

In [9]:
mat = np.array([[1, 2], [3, 4]])
mat

array([[1, 2],
       [3, 4]])

In [10]:
mat[0, 1] # accessing the ele

np.int64(2)

In [11]:
c = np.ones([2, 3])
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.transpose(c) # this is not done in-place

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 0], [0, 1]])
A*B

array([[1, 0],
       [0, 4]])

CAUTION: Multiplies corresponding elements only, not matrix multiplication

In [14]:
A@B

array([[1, 2],
       [3, 4]])

In [15]:
np.matmul(A, B)

array([[1, 2],
       [3, 4]])

In [16]:
D = np.ones([2,2,2])
D

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [19]:
E = np.ones([4, 2,3])
E

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
np.sum(D)

np.float64(8.0)

In [21]:
np.mean(D)

np.float64(1.0)

In [21]:
np.shape(D)

(2, 2, 2)